### ISSUE TITLE
Intel giving just abstract image

### ISSUE THREAD

**Issue by enzyme69** [liuliu/swift-diffusion#10]
![txt2img_4160646034](https://user-images.githubusercontent.com/3952687/198959142-a47efb2e-dadd-4e7d-bd4a-448c408105be.png)

![txt2img_1547624426](https://user-images.githubusercontent.com/3952687/198959173-93b788e7-81e6-4e1c-acc4-2ee6d6175b6c.png)

Back to Intel computer, this is weird, I kept getting only these abstract image after 10 minutes. This is 20 steps sample.

Any idea why?

**Comment by enzyme69** [comment]
Hmm... my feeling is that I am using the wrong model...

**Comment by enzyme69** [comment]
Downloaded the ckpt that you supplied and it's good now. Is it possible to have 1.5 version?

**Comment by liuliu** [comment]
There are still some problems with sd-v1.5 with Float16 unfortunately (I haven't got time to dig deep, seems really about precision so far). Anyway, I put the weights under https://static.libnnc.org/sd-v1.5.ckpt feel free to try. The new autoencoder I put it under https://static.libnnc.org/vae_ft_mse_840000_f32.ckpt you need to make a few code changes to use the new autoencoder (in examples/txt2img/main.swift, change the file path). For what it is worth, I uploaded [wd-v1.3.ckpt](https://static.libnnc.org/sd-v1.5.ckpt) too, and this definitely needs the new autoencoder (you cannot load the decoder from that file).

**Comment by enzyme69** [comment]
Thanks Liuliu! I will try!
