### ISSUE TITLE
FYI: merging with miniSD model

### ISSUE THREAD

**Issue by ClashSAN** [liuliu/swift-diffusion#21]
@liuliu this model when its unique properties are transferred to any other model do very well at small sizes: 192x256, 256x320

https://huggingface.co/ClashSAN/miniSD-anything-vae-swapped

I can observe the generating at 192x256 takes very low ram usage.
if you go further and use a quantized model you take 0.7gb with onnx.
https://huggingface.co/ClashSAN/miniSD-quantized-onnx

**Comment by liuliu** [comment]
Thanks! I integrated MiniSD from Justin a while ago, but now more interested in the Teacher-Student trained small-diffusion.
