### ISSUE TITLE
[Feature Request] LoRA(Low-Rank Adaptation of Large Language Models) Support

### ISSUE THREAD

**Issue by Cairetina** [liuliu/swift-diffusion#23]
See:
https://huggingface.co/blog/lora
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/855b9e3d1c5a1bd8c2d815d38a38bc7c410be5a8

**Comment by AugustRush** [comment]
+1

**Comment by liuliu** [comment]
https://github.com/liuliu/swift-diffusion/blob/main/examples/lora/main.swift
https://github.com/liuliu/swift-diffusion/blob/main/examples/txt2img/main.swift#L193
