### ISSUE TITLE
Randomizing SEED for Swift Diffusion

### ISSUE THREAD

**Issue by enzyme69** [liuliu/swift-diffusion#3]
Is there option to randomize seed from command? 

I get image 80-90 seconds on M1 iMac 8GB. This is cool!

**Comment by enzyme69** [comment]
Ok I found the SEED control inside the actual swift example code.

I am curious if I need to compile each time and run the command via terminal, because that's what I have been doing so far. 

Using M1 Mac 8 GB, I can apparently get an image every 50-60 seconds. 

If I change the code in Swift, can I loop and get 100 generation with different seed?

**Comment by enzyme69** [comment]
My solution was like this:
```swift
let randomInt = Int.random(in: 0..<432896)
let randomUINT = UInt32(randomInt)


DynamicGraph.setSeed(randomUINT)
DynamicGraph.memoryEfficient = true
```

**Comment by liuliu** [comment]
It can be simplified to:
```
let randomUINT = UInt32.random(in: UInt32.min...UInt32.max)
```
Alternatively, you can also remove the `DynamicGraph.setSeed(42)` line entirely. But I recommend you generate a random seed explicitly for easier reproducibility.
