### ISSUE TITLE
Rare and non reproducible random crashes 

### ISSUE THREAD

**Issue by ghost** [liuliu/swift-diffusion#37]
I've seen that sometimes it just randomly crashes and gives a seg fault. 

ive seen that the draw things app also crashes sometimes like that. 

it could be when other processes are taking GPU memory or something.

**Comment by ghost** [comment]
I have a feeling that it happens in transferring data b/w GPU/CPU in mps

**Comment by liuliu** [comment]
Hi, if you have stacktrace, that would be helpful!

Also, s4nnc is largely not thread-safe, and meant to be operated within one thread, that might / might not be relevant.

**Comment by ghost** [comment]
I am not able to reproduce it again. 
Thanks
