### ISSUE TITLE
Why a separate UNetv2?

### ISSUE THREAD

**Issue by ghost** [liuliu/swift-diffusion#38]
I thought for SD2 Unet was the same, only difference was in the text encoder which produces 1024 channels.

**Comment by ghost** [comment]
It looks like you are changing the number of heads

**Comment by liuliu** [comment]
https://www.reddit.com/r/StableDiffusion/comments/z42yph/some_notes_on_porting_sd2_over_to_iphone_or_other/

**Comment by ghost** [comment]
Thanks

**Comment by ghost** [comment]
I was inspecting sd_v2.1_f16.ckpt ( from your website ) and i saw that the weights were not matching with the torch version at https://huggingface.co/stabilityai/stable-diffusion-2-1/blob/main/v2-1_768-ema-pruned.ckpt . 

which torch file did you convert it from?

**Comment by ghost** [comment]
I think you are using this one  : https://huggingface.co/stabilityai/stable-diffusion-2-1-base/resolve/main/v2-1_512-ema-pruned.ckpt

**Comment by liuliu** [comment]
Yeah, 768-v file are labelled as `sd_v2.1_768_v_f16.ckpt`
