### ISSUE TITLE
Any chance you could share all the .ckpt files used in the canny2img example?

### ISSUE THREAD

**Issue by ghost** [liuliu/swift-diffusion#39]

**Comment by liuliu** [comment]
These are the same you downloaded from the Draw Things app (and if you sniff the traffic, these are from https://static.libnnc.org/controlnet_scribble_2.x_f16.ckpt and sd v2.1 models (probably sd_v2.1_f16.ckpt))

**Comment by ghost** [comment]
[sd_v2.1_f16.ckpt](https://static.libnnc.org/sd_v2.1_f16.ckpt) only has unet weights not text encoder and others.

**Comment by ghost** [comment]
actually they are in : open_clip_vit_h14_f16.ckpt

**Comment by liuliu** [comment]
Yeah, later models (all accessible through https://static.libnnc.org/xxx) have text encoder / autoencoder weights separated out.
