### ISSUE TITLE
Checkpoint Custom?

### ISSUE THREAD

**Issue by enzyme69** [liuliu/swift-diffusion#4]
I read somewhere that the .ckpt here is not like ckpt we can just download online, I have few others like: waifu diffusion, robo diffusion, etc. which I want to use, but I wonder how it works if I like to use those?

**Comment by liuliu** [comment]
That's correct. One thing about this implementation is that it has no Python dependency at all, no need to deal with anaconda or miniconda or pip on macOS platforms, which can be painful.

However, to use other .ckpt, you need to setup Python environment with `ldm`. Follow: https://invoke-ai.github.io/InvokeAI/installation/INSTALL_MAC/ I recommend use miniconda route, seems work better for me.

After that, you can run `bazel run examples:unet` to generate `unet.ckpt`, which provides the unet model. Of course, checkout the source code, I hard-coded a few paths there: https://github.com/liuliu/swift-diffusion/blob/main/examples/unet/main.swift#L806

To load the new model, change this line to load it from that new file: https://github.com/liuliu/swift-diffusion/blob/main/examples/txt2img/main.swift#L119

Note that I loaded both unet and decoder from that file. For many of the tuned models, I don't think they tuned the autoencoder, you can still use the older decoder.

If you want to generate model with new encoder (for img2img) / decoder, checkout `examples/decoder/main.swift` and `examples/encoder/main.swift`, both can be invoked from command line with `bazel run examples:decoder`.

*I think* these should work on macOS platforms, I don't think that I tried. I converted weights on my workstation with NVIDIA cards, there may be some strangeness or outright doesn't work on macOS though.

**Comment by enzyme69** [comment]
Thanks, maybe beyond my scope for now but interesting, I will study the one that works on my M1 first. Intel one is outputting grey only. Wonder what's failed.

**Comment by liuliu** [comment]
No worries. I plan to convert a few models and put it up (I have waifu converted, but forget to put it up). sd-v1.5 have some issues with FP16 for me, so I haven't put that up yet.
