### ISSUE TITLE
LoRA layers not present in UNet

### ISSUE THREAD

**Issue by ghost** [liuliu/swift-diffusion#42]
There is an exampe for lora but the layers are not present in the Unet class.

**Comment by liuliu** [comment]
There are two ways to implement LoRA. One is to have aux multiplications done at runtime along with the main one (a.k.a. LoRA layers). Another is to merge the weights first. We opt to merge the weight to keep the network the same so we can reuse things such as CoreML too.

**Comment by ghost** [comment]
Okay thanks
