### ISSUE TITLE
Support for macOS Sonoma

### ISSUE THREAD

**Issue by ghost** [liuliu/swift-diffusion#44]
Currently it does not work on macOS Sonoma. 
I tried running DrawThings.ai on Sonoma and it did not work. It crashes. 

What could be causing this issue?

**Comment by liuliu** [comment]
Might be related to that in the newer OS, the MPSGraph executable optimization level updated to 1.

**Comment by ghost** [comment]
Thanks, what could be a possible fix?

**Comment by liuliu** [comment]
Can you help to test if uncomment this line: https://github.com/liuliu/ccv/blob/unstable/lib/nnc/mps/ccv_nnc_mps.m#L426 and change it to Level0 would be sufficient to run it again?

**Comment by ghost** [comment]
Okay i will let you know.

**Comment by ghost** [comment]
This fixes the issue. Thanks.
