### ISSUE TITLE
Why are there two UNets in SDXL?

### ISSUE THREAD

**Issue by ghost** [liuliu/swift-diffusion#51]
Why is there a UNet and Unet_fixed?
Is that some optimization to save memory?

**Comment by ghost** [comment]
Its an interesting idea, that you pre-compute   the keys and values of the next encoder part. 
But does that give any significant memory gains?

**Comment by liuliu** [comment]
It saves about 600MiB RAM (Float16, less if it is 8-bit model). Computation saving is negligible (you don't need to compute these on every iteration, hence computation saving).
