### ISSUE TITLE
How to load weights into model?

### ISSUE THREAD

**Issue by davidw0311** [liuliu/swift-diffusion#55]
Hello, I am having difficulty trying to run txt2img on my macbook pro M1. I downloaded the sd-v1.4.ckpt from the link in the readme, but run into the same issue as https://github.com/liuliu/swift-diffusion/issues/49

In trying to debug this, when I print all the keys from the checkpoint, I notice they are labeled as:
<img width="1464" alt="image" src="https://github.com/liuliu/swift-diffusion/assets/43504578/c3244fd0-b124-4298-a9c0-38f7bc742d6b">

So I am wondering if 
![image](https://github.com/liuliu/swift-diffusion/assets/43504578/ad56b60f-cd53-447a-af57-ca57dbcf1da4)

is the correct way to load the weights into the model (and similarly for the text model and encoder/decoder?

However, I am still getting nan values as the output from my decoder at the end, wondering if this is related to the weight loading or something else?

Thank you!

**Comment by limengf1218** [comment]
Loading with
`graph.openStore("path_to_sd1.5.ckpt") { store in
    store.read("text_model", model: textModel)
  }`

is working, but the problem seems to be using the LoRAUnet or LoRACLIPTextModel. Loading with UNet() and CLIPTextModel instead works
