### ISSUE TITLE
Intel one, grey or weird abstract output

### ISSUE THREAD

**Issue by enzyme69** [liuliu/swift-diffusion#6]
What happened if the output is like this after 742 seconds.
<img width="519" alt="Screenshot 2022-10-23 at 11 47 31 am" src="https://user-images.githubusercontent.com/3952687/197367887-0e305f03-6689-4a12-a6dc-8584bf7f70bb.png">

It was just grey plan 512x512 pixel, but I remember that I forgot to do this on Intel MacBookPro I am testing now:
`echo "build --config=mps" > .bazelrc.local`

**Comment by liuliu** [comment]
Looks like the random noise initialization have some issues for you. Are you on `main` branch o `liu/nhwc` branch?

And yes, without enabling MPS, it won't work.

**Comment by enzyme69** [comment]
I think I am using main branch.

**Comment by enzyme69** [comment]
Ok after using nhwc, I can say it's working and I got output! 10 minutes / 600 seconds each, but it's working. Thanks!

![txt2img_892205878](https://user-images.githubusercontent.com/3952687/197384310-570798fe-2ce6-4d52-aff7-d50fc7ae30f4.png)

**Comment by liuliu** [comment]
Cool. I will take a look what's going on with main branch on Intel. Probably something straightforward.

**Comment by ghost** [comment]
@liuliu  did you figure out what the issue was?

**Comment by liuliu** [comment]
I think it is just missing the weight file.
